<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE business-cards [
    <!ELEMENT business-cards (business-card+)>
    <!ELEMENT business-card (name, phone+, email)>
    <!ATTLIST phone type (home | work | mobile) #REQUIRED>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT phone (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
]>
<business-cards>

    <business-card>
        <name>Rorie Demanche</name>
        <phone type="home">17101534949</phone>
        <phone type="work">15033193558</phone>
        <phone type="mobile">11827481667</phone>
        <email>rdemanche0@foxnews.com</email>
    </business-card>

    <business-card>
        <name>Kelcey Surman</name>
        <phone type="home">12499267376</phone>
        <phone type="work">12083636588</phone>
        <phone type="mobile">19825366860</phone>
        <email>ksurman1@usnews.com</email>
    </business-card>

    <business-card>
        <name>Simon Heddan</name>
        <phone type="home">16878084290</phone>
        <phone type="work">16048157810</phone>
        <phone type="mobile">19241743271</phone>
        <email>sheddan2@alexa.com</email>
    </business-card>

    <business-card>
        <name>Chan Supple</name>
        <phone type="home">15771652495</phone>
        <phone type="work">15479347337</phone>
        <phone type="mobile">13676670747</phone>
        <email>csupple3@123-reg.co.uk</email>
    </business-card>

</business-cards>
